on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths-ignore:
      - "**/*.md"

name: 🧪 Run Tests
jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        config: [Release, Debug]
        type: [gcc, clang, msvc, clang-cl]

        include:
          - type: gcc
            os: ubuntu-latest
            container: archlinux:base-devel
            deps: pacman --noconfirm -Syu git cmake gcc ninja make

          - type: clang
            os: ubuntu-latest
            container: archlinux:base-devel
            deps: pacman --noconfirm -Syu git cmake clang ninja make

          - type: msvc
            os: windows-latest

          - type: clang-cl
            os: windows-latest
            cmake_args: -T ClangCL -A x64

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    name: "${{ matrix.type }} (⚙️: ${{ matrix.config }})"

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4

      - name: 🧰 Dependencies
        run: ${{ matrix.deps }}

      - name: 🔧 Compile
        run: |
          cmake -B build -Drebind_tests=ON ${{ matrix.cmake_args }}
          cmake --build build --config ${{ matrix.config }}

      - name: 🔬 Run Tests
        run: |
          ctest --test-dir build/tests -C ${{ matrix.config }} --verbose
